---
software:
  name: Veeva CLM Builder

clm:
 customFields:
  veevaTrackSubsceneField:
 ftp:
  email:
  host:
  user:
  pass:
  remotePath: '/ctlfile'
 product:
  name: 'veeva'
  suffix: '-'
 primary:
  name: 'veeva-v1'
  key_messages:
  - key_message: 'home'
    description: 'Home'
    display_order: '0'
    slides:
    - slide: 'home'
      id: '0'
  - key_message: 'overview'
    description: 'Veeva Test Overview'
    display_order: '1'
    slides:
    - slide: 'Veeva Test Overview'
      id: '2-0'
  - key_message: 'sitemap'
    description: 'Sitemap'
    display_order: '2'
    slides:
    - slide: 'Sitemap'
      id: '0-1'
  - key_message: 'resources'
    description: 'Resources'
    display_order: '3'
    slides:
    - slide: 'Resources'
      id: '0-2'
 assets:
  name: 'veeva-assets-v1'
  key_messages:
  - key_message: 'prescribing-information'
    description: 'Prescribing Information'
    display_order: 0
  - key_message: 'patient-brochure'
    description: 'Patient Brochure'
    display_order: 2

paths:
    src: 'app'
    dist: 'build'
    deploy: 'deploy'
    tmp: 'build/.tmp'
    pages: 'templates/pages'
    layouts: 'templates/layouts'
